const SUCCESS_CODE = 200
const BAD_REQUEST_CODE = 400
const FORBIDDEN_CODE = 403
const INTERNAL_SERVER_ERROR_CODE = 500

export {
  SUCCESS_CODE,
  BAD_REQUEST_CODE,
  FORBIDDEN_CODE,
  INTERNAL_SERVER_ERROR_CODE
}
